name: Miles Retrieval

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: check out repo
      uses: actions/checkout@v2

    # - name: use node
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '18.x'
    # - name: install node dependencies
    #   run: npm ci
    # - name: update miles
    #   run: npm run update-ytd-distance

    - name: Fetch data
      uses: JamesIves/fetch-api-data-action@v2
      with:
        token-endpoint: https://www.strava.com/api/v3/oauth/token
        token-configuration: '{ "method":"POST", "headers": {"Accept": "application/json, text/plain, */*", "Content-Type": "application/json"}, "body": {"client_id": "99458", "client_secret": "${{ secrets.STRAVA_CLIENT_SECRET }}", "refresh_token": "${{ secrets.STRAVA_REFRESH_TOKEN }}", "grant_type": "refresh_token", "redirect_uri": "http://localhost"} }'
        endpoint: https://www.strava.com/api/v3/athlete/activities/
        configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer {{{ data.access_token }}}"} }'